version: '3'

services:
  deno:
    environment:
      https_proxy: ${https_proxy:-''}
      http_proxy: ${http_proxy:-''}
      no_proxy: ${no_proxy:-''}
      NO_PROXY: ${no_proxy:-''}
      HTTPS_PROXY: ${https_proxy:-''}
      HTTP_PROXY: ${http_proxy:-''}
    ports:
      - "8000:8000"
    build: .
    volumes:
      -  .:/opt/app
